<exceptionDefinitions>
    <errorGroup name="DATASOURCE" mask="8">
        <description></description>
        <errorCode id="1" name="LOAD_OBJECT">
            <description>Error loading object</description>
            <message>Failed to load object [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="CREATE_OBJECT">
            <description>Error creating object</description>
            <message>Failed to create object [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="FAILED_EXECUTE_BATCH">
            <description>Error executing batch</description>
            <message>Failed executing batch operation:[{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="NO_ADD_ERROR">
            <description>No permission to add statements</description>
            <message>Attempted to add triple [{0}] [{1}] [{2}] to named graph [{3}] that either does not exist, or does not have add permission</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="NO_REMOVE_ERROR">
            <description>No permission to remove statements</description>
            <message>Attempted to remove triple [{0}] [{1}] [{2}] to named graph [{3}] that either does not exist, or does not have remove permission</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="NO_READ_ERROR">
            <description>No permission to read statements</description>
            <message>Attempted to read triples from NamedGraph [{0}] that either does not exist, or does not have read permission</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="7" name="NO_INSERT_NAMEDGRAPH_ACL_ERROR">
            <description>No permission to add namedgraph</description>
            <message>No permission to insert NamedGraph [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="NO_REMOVE_NAMEDGRAPH_ACL_ERROR">
            <description>No permission to remove namedgraph</description>
            <message>No permission to remove NamedGraph [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="COMMAND_PREREQ_FAILED">
            <description>Command precondition</description>
            <message>Command [{0}] failed to commit due to precondition not being met. [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="NO_ADD_RESERVED_URI">
            <description>Trying to add reserved predicate</description>
            <message>Failed to add a reserved URI:[{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="11" name="FIND_STATEMENTS">
            <description></description>
            <message>Could not execute find statements in datasource [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="NO_LOCK_NAMEDGRAPHS">
            <description></description>
            <message>Could not lock the NamedGraphs needed for transaction [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="PREVIOUS_TRANSACTION_FAILED">
            <description></description>
            <message>Previous transaction failed involving graph [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="STATEMENT_NO_GRAPH">
            <description></description>
            <message>Import contained statements with no named graph specified.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="ERROR_UPDATE_LISTENER">
            <description></description>
            <message>Error in update listener:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorGroup name="NAMEDGRAPH" mask="12">
            <errorCode id="1" name="NOT_FOUND">
                <description></description>
                <message>NamedGraph [{0}] not found</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="2" name="INVALID_METADATA_TRIPLE">
                <description></description>
                <message>Failed to insert triple ({0}) into metadata graph {1}, because an insert rule for a reserved predicate was not met.</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="3" name="NON_REVISIONED_GRAPH">
                <description></description>
                <message>NamedGraph [{0}] is a non revisioned graph</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="4" name="NAMED_GRAPH_TYPE_INCORRECT">
                <description></description>
                <message>NamedGraph {0} is an unsupported type of graph for this operation.</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="5" name="REVISION_NOT_FOUND">
                <description></description>
                <message>Revision [{0}] of NamedGraph [{1}] not found</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="6" name="GET_SIZE">
                <description></description>
                <message>Could not get size of NamedGraph [{0}]</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="7" name="GET_UUID">
                <description></description>
                <message>Could not get the UUID of NamedGraph [{0}]</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="8" name="GET_URI">
                <description></description>
                <message>Could not get the URI of NamedGraph [{0}]</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="9" name="CANNOT_WRITE_TO_A_SYSTEM_GRAPH">
                <description></description>
                <message>{0} is a system graph which cannot be changed by a user.</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
            <errorCode id="10" name="GRAPH_NOT_VALID">
                <description></description>
                <message>Named graph with UUID:[{0}] not valid at this time.</message>
                <possibleCause></possibleCause>
                <suggestedFix></suggestedFix>
            </errorCode>
        </errorGroup>
        <errorCode id="20" name="FAILED_CREATING_CONNECTION">
            <description></description>
            <message>Failed to create a datasource connection. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="FAILED_RETURNING_CONNECTION">
            <description></description>
            <message>Failed to return a datasource connection. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="FAILED_START_TRANSACTION">
            <description></description>
            <message>Failed to start datasource transaction. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="FAILED_COMMIT_TRANSACTION">
            <description></description>
            <message>Failed to commit datasource transaction. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="24" name="FAILED_ROLLBACK_TRANSACTION">
            <description></description>
            <message>Failed to rollback datasource transaction. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="25" name="FAILED_INITIALZE_CONNECTION">
            <description></description>
            <message>Failed to initialize datasource connection. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="COMBUS" mask="14">
        <errorCode id="1" name="COULD_NOT_PUBLISH">
            <description></description>
            <message>Could not publish message to notification service:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="PROCESS_UPDATE_FAILED">
            <description></description>
            <message>Failure processing Update Message:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="JMS_REGISTER_SELECTOR_ERROR">
            <description></description>
            <message>Tracker could not be registered with JMS selector [{0}] :{1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="JMS_UNREGISTER_SELECTOR_ERROR">
            <description></description>
            <message>Tracker could not be unregistered with JMS selector [{0}] :{1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="JMS_CONNECT_TIMEOUT">
            <description></description>
            <message>Timeout connecting to JMS server</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="7" name="JMS_CONNECT_FAILED">
            <description></description>
            <message>Error connecting to JMS server:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="NOTIFICATION_SERVICE_ERROR">
            <description></description>
            <message>No Notification Service was created.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="NO_SERVER_RESPONSE">
            <description></description>
            <message>No Response from Server for request {0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="SERVER_CONNECT_EXCEPTION">
            <description></description>
            <message>Could not create connection to notification server due to server problem:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="11" name="JMS_MESSAGE_PARSING">
            <description></description>
            <message>JMS exception unpacking method and transaction id from transaction complete message:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="12" name="JMS_MISSING_MESSAGE_PARAMETER">
            <description></description>
            <message>JMS Message missing message parameter.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="JMS_DISCONNECT_FAILED">
            <description></description>
            <message>Error disconnecting from JMS server:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="JMS_CREATE_PRODUCER_FAILED">
            <description></description>
            <message>Could not create a producer for destination [{0}]:{1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="JMS_ALREADY_CONNECTED">
            <description></description>
            <message>Already connected to notification service</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="JMS_NOT_CONNECTED">
            <description></description>
            <message>Not connected to notification service</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="NO_SUCH_DESTINATION">
            <description></description>
            <message>Unknown Destination {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="18" name="INTERRUPTED">
            <description></description>
            <message>Waiting for response for {0} interrupted</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="JMS_FAILED_SETTING_MESSAGE_PARAMETER">
            <description></description>
            <message>Error setting message parameter:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="JMS_AUTHENTICATION">
            <description></description>
            <message>User no longer authenticated or valid on the server</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="JMS_SERVICE_EXCEPTION">
            <description></description>
            <message>Unknown server exception executing request {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="CREATE_BROKER_FAILED">
            <description>Failed to create an embedded ActiveMQ broker</description>
            <message>Failed to create an embedded ActiveMQ broker</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="STOP_BROKER_FAILED">
            <description>Failed to stop the embedded ActiveMQ broker</description>
            <message>Failed to stop the embedded ActiveMQ broker</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="24" name="NOT_AUTHORIZED_FOR_TOPIC">
            <description>User is not authorized to register with the given topic</description>
            <message>User {0} not authorized to subscribe for topic {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="25" name="SEND_MESSAGE_FAILED">
            <description>Sending message failed</description>
            <message>Sending message to [{0}] failed</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="26" name="CREATE_MESSAGE_FAILED">
            <description>Error creating a JMS message</description>
            <message>Error creating a JMS message</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="27" name="NO_UUID_ERROR">
            <description>No UUID for namedGraph was found, so could not subscribe to namedGraph''s topic</description>
            <message>No UUID for namedGraph [{0}] was found, so could not subscribe to namedGraph''s topic</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="28" name="INVALID_TOPIC">
            <description>Invalid topic</description>
            <message>Invalid topic: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="RECORDER_ERROR">
            <description>Recorder Error</description>
            <message>Recorder Error: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="SSL_MISMATCH">
            <description>SSL required is true, but ssl not setup.</description>
            <message>SSL required is true, but ssl host and port not set</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="31" name="BAYEUX_NULL">
            <description></description>
            <message>EncryptedTokenAuthenticationJSONTransport requires reference to valid Bayeux object</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="32" name="ERROR_PURGING_TOPICS">
            <description></description>
            <message>Error Purging ActiveMQ Topics</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="33" name="ERROR_LOGGING_IN">
            <description></description>
            <message>Unknown user or invalid password.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="34" name="ERROR_CONNECTION_NOT_AUTHENTICATED">
            <description></description>
            <message>Connection is not authenticated:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="35" name="ERROR_USER_NOT_AUTHENTICATED">
            <description></description>
            <message>User {0} is not authorized for operation {1} on destination {2}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="36" name="ERROR_SERVER_NOT_READY">
            <description></description>
            <message>Server is not ready to accept subscriptions, since a primary datasource is not yet active.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="37" name="ERROR_TOPIC_NOT_EXIST_YET">
            <description></description>
            <message>User {0} is not authorized to subscribe to: {1} since is does not yet exist</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="38" name="ERROR_DISCONNECTING_NOTIFICATIONS">
            <description></description>
            <message>Error disconnecting from notifications</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="39" name="ERROR_PROCESSING_MESSGE">
            <description></description>
            <message>Error processing message:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="40" name="ERROR_CHANNEL_LISTENER">
            <description></description>
            <message>Error in statement channel listener:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="41" name="ERROR_CLOSING_COMPONENT">
            <description></description>
            <message>Error closing jms {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
         <errorCode id="42" name="RUNAS_NOT_AUTHORIZED">
            <description></description>
            <message>User must be a sysadmin to runas another user.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="SERVER" mask="15">
        <errorCode id="1" name="RESET_NOT_ENABLED">
            <description></description>
            <message>Reset is disabled</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="ERROR_SEARCHING_USERS">
            <description></description>
            <message>Error while authenticating user:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="USERID_MULTIPLE_USERS">
            <description></description>
            <message>User ID maps to multiple ldap users:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="UNKNOWN_USER_ERROR">
            <description></description>
            <message>Unknown user error:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="INIT_FILE">
            <description></description>
            <message>Initialization file ({0}) not found</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="NO_SERVER_CONFIG">
            <description></description>
            <message>Servlet properties not set.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="REPLICATION_FAILED">
            <description></description>
            <message>Error during replication:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="MISSING_ARG">
            <description></description>
            <message>Missing {0} for operation {1}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="BAD_USER_PASSWORD">
            <description></description>
            <message>Request did not contain valid username and password</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="UPDATE_SERVER_ERROR">
            <description></description>
            <message>Errors updating server.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="20" name="GET_ROLES_FOR_GRAPH_ERROR">
            <description></description>
            <message>Failed to get roles for NamedGraph {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="GET_STORED_GRAPHS_ERROR">
            <description></description>
            <message>Failed to get stored NamedGraphs for user {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="UNKNOWN_OPERATION_ERROR">
            <description></description>
            <message>Unknown server operation error [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="24" name="QUERY_FAILED_ERROR">
            <description></description>
            <message>Error executing query [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="25" name="UNKNOWN_SERVER_ERROR">
            <description></description>
            <message>Unknown server: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="28" name="LDAP_ERROR">
            <description></description>
            <message>Internal error within ldap:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="NO_PRINCIPAL_ERROR">
            <description></description>
            <message>No user principal found within IOperationContext</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="REPLICATION_ARGUMENTS_FAILED">
            <description></description>
            <message>Replicate request contains invalid statements. Subjects must be URIs and objects must be revision numbers.Subject [{0}], Object [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="31" name="FAILED_AUTHENTICATE_USER">
            <description></description>
            <message>Failed to authenticate user:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="32" name="ERROR_GETTING_FROM_POOL">
            <description></description>
            <message>Error getting client from pool</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
		<errorCode id="44" name="INSTALL_LDAP_FAILED_TEST_SEARCH">
            <description></description>
            <message>Test search occurred, but found no results.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="45" name="INSTALL_LDAP_INVALID_CONFIGURATION">
            <description></description>
            <message>Invalid LDAP configuration.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="33" name="INSTALL_LDAP_NO_LDAP_COMPONENT">
            <description></description>
            <message>No ldap component found in supplied data.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        
        <errorCode id="35" name="INSTALL_LDAP_ADMIN_BIND">
            <description></description>
            <message>Invalid LDAP configuration. Could not bind with admin dn [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="36" name="INSTALL_LDAP_ADMIN_SEARCH">
            <description></description>
            <message>Invalid LDAP configuration. Search for test user failed.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="37" name="INSTALL_LDAP_USER_BIND">
            <description></description>
            <message>Invalid LDAP configuration. Could not bind with test user [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        
          <errorCode id="38" name="INSTALL_DATABASE_JDBC_URL_NOT_SET">
            <description></description>
            <message>The database jdbc connection string is not set.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="39" name="INSTALL_DATABASE_USER_NOT_SET">
            <description></description>
            <message>The database user is not set.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="40" name="INSTALL_DATABASE_TYPE_NOT_SET">
            <description></description>
            <message>The database type is not set.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="41" name="INSTALL_DATABASE_CANNOT_CONNECT">
            <description></description>
            <message>Failed to connect to the database.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
       <errorCode id="42" name="INSTALL_DATABASE_NO_RDB_COMPONENT">
            <description></description>
            <message>No rdb component found in supplied data.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="43" name="ANONYMOUS_UPDATE_NOT_ALLOWED_ERROR"> 
            <description>Anonymous users cannot create or update data.</description> 
            <message>Anonymous users cannot create or update data.</message> 
            <possibleCause></possibleCause> 
            <suggestedFix></suggestedFix> 
        </errorCode> 
    </errorGroup>

    <errorGroup name="IO" mask="16">
        <errorCode id="1" name="PROPERTIES_ERROR">
            <description></description>
            <message>Error with configuration properties</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="WRITE_ERROR">
            <description></description>
            <message>IO write error:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="READ_ERROR">
            <description></description>
            <message>IO read error:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="ERROR_CONVERT_STRING_SET">
            <description></description>
            <message>Error converting String To Set - Unknown format: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="NODE_LABEL_ERROR">
            <description></description>
            <message>Node label must not be null for bnode: [{0}] (it may be that this blank node was created with a different blank node manager than the one in Constants.valueFactory)</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="USER_ENCODE_ERROR">
            <description></description>
            <message>Failed to encode user name and password for service call endpoint.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="7" name="UNSUPPORTED_DATATYPE">
            <description></description>
            <message>Unsupported datatype. Must be either {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="INVALID_DATETIME">
            <description></description>
            <message>Invalid Timestamp. Nanoseconds must not be negative. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="ENCODING_ERROR">
            <description></description>
            <message>Error with encoding:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="UNSUPPORTED_FORMAT_ERROR">
            <description></description>
            <message>Unsupported RDF format:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="DESERIALIZATION_ERROR">
            <description>Error deserializing data.</description>
            <message>Error deserializing data:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="MISSING_PARSER">
            <description>Could not find parser for format.</description>
            <message>Could not find parser for format:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="RDF_PARSER_ERROR">
            <description>Error parsing RDF.</description>
            <message>Error parsing RDF with format:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="RDF_HANDLER_ERROR">
            <description>Error with RDF Handler while parsing RDF.</description>
            <message>Error with RDF Handler while parsing RDF with format:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="18" name="UNKNOWN_EXTENSION_RDF_FORMAT_ERROR">
            <description>No RDF format found for given file extension.</description>
            <message>No RDF format found for given file extension:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="UNKNOWN_MIME_RDF_FORMAT_ERROR">
            <description>No RDF format found for given mime type.</description>
            <message>No RDF format found for given mime type:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="NO_WRITER_FOR_MIMETYPE_ERROR">
            <description>No RDF writer found for given mime type.</description>
            <message>No RDF writer found for given mime type:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="NO_GRAPH_SUPPORT_RDFFORMAT">
            <description>The given RDFFormat does not support namedgraphs.</description>
            <message>The given RDFFormat does not support namedgraphs:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="ERROR_SERIALIZING_JSON">
            <description></description>
            <message>Error Serializing json message</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="CLIENT" mask="17">
        <errorCode id="1" name="CLIENT_NOT_CONNECTED">
            <description></description>
            <message>Client not connected.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="CLIENT_CLOSED">
            <description></description>
            <message>Client already closed.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="LOCAL_PERSISTENCE_ERROR">
            <description></description>
            <message>Error in local persistence:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="FAILED_ADD_TRIPLES">
            <description></description>
            <message>Failed to add triples to TransactionGraph:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="FAILED_DELETE_TRIPLES">
            <description></description>
            <message>Failed to delete triples to TransactionGraph:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="DB_ALREADY_OPEN">
            <description></description>
            <message>The database specified is currently open: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="XCOMMAND_LINK_ERROR">
            <description></description>
            <message>InputCommand must already be in CommandVector:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="FAILED_CLEAR">
            <description></description>
            <message>Failed to clear database container for NamedGraph [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="FAILED_INITIALIZE_CONTAINER">
            <description></description>
            <message>Failed to initialize database container: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="31" name="FAILED_INITIALIZE_CONTAINER_CONNECTION">
            <description></description>
            <message>Could not initialized physical storage because database connection is not setup</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="32" name="FAILED_INITIALIZE_CONTAINER_TABLES">
            <description></description>
            <message>Could not initialize database tables: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="34" name="FAILED_INITIALIZE_CONTAINER_SQLCACHE">
            <description></description>
            <message>Could not initialize containers sqlcache: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="36" name="FAILED_CONTAINER_INSERT_BATCH">
            <description></description>
            <message>Failed executing batched insertStatement: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="37" name="FAILED_CONTAINER_FIND_NODE">
            <description></description>
            <message>Failed finding node: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="38" name="FAILED_CONTAINER_STMT_EXISTS">
            <description></description>
            <message>Failed determining if statements exists in database: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="39" name="FAILED_CONTAINER_FIND_STATEMENTS">
            <description></description>
            <message>Failed finding statements in database: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="40" name="FAILED_CONTAINER_DELETE_STATEMENT">
            <description></description>
            <message>Failed deleting statement from database: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="41" name="FAILED_CONTAINER_COUNT_STATEMENTS">
            <description></description>
            <message>Failed counting statements in database for namedGraph [{0}] : [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="43" name="FAILED_CONTAINER_EXEC_QUERY">
            <description></description>
            <message>Error executing sparql query [{0}]:[{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="44" name="FAILED_CONTAINER_COUNT_ROWS">
            <description></description>
            <message>Failed counting statements in database for table [{0}] : [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="45" name="NO_COLON_IN_URI">
            <description></description>
            <message>No colon in URI: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="46" name="NO_NULL_VALUES">
            <description></description>
            <message>None of the values can be null, NAMEDGRAPHURI=[{0}], SUBJ=[{1}] , PROP=[{2}] ,OBJ=[{3}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="47" name="SPACE_IN_URI">
            <description></description>
            <message>Space in URI: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="48" name="URI_NOT_NULL">
            <description></description>
            <message>NamedGraph URI cannot be null</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="49" name="NO_MAPPING">
            <description></description>
            <message>Could not find automatic mapping of Java object to an RDF typed literal:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="50" name="ERROR_PARSING_QUERY">
            <description></description>
            <message>Error parsing query, [{0}]: [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="51" name="CLIENT_LOCK_ERROR">
            <description></description>
            <message>There was an internal error in the client due to a locking issue.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="52" name="JMS_NOT_ENABLED">
            <description></description>
            <message>Operations requiring JMS connectivity are not available to this client</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="53" name="COMMAND_ERROR">
            <description></description>
            <message>Error executing command:[{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="54" name="INVALID_URI">
            <description></description>
            <message>Invalid URI:[{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="55" name="CURIE_ERROR">
            <description></description>
            <message>CURIE must has a prefix and fragment separated by a '':''.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="56" name="NO_VALUEFACTORY_MAPPING">
            <description></description>
            <message>Mapping for ''{0}'' not registered with this value factory.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="57" name="VARIABLE_START_QUESTION">
            <description></description>
            <message>Variable name may not begin with ''?''</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="58" name="VARIABLE_NO_SPACES">
            <description></description>
            <message>Variable name may not contain whitespace chars.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="59" name="FAILED_INITIALIZE_GRAPH">
            <description></description>
            <message>Failed to initialize named graph: [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="60" name="FAILED_NOTIFYING_ADD_STATEMENTS">
            <description></description>
            <message>Failed calling listener's add statements: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="61" name="FAILED_NOTIFYING_REMOVE_STATEMENTS">
            <description></description>
            <message>Failed calling listener's remove statements: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="62" name="EXTRA_REPLICATION_NEEDED">
            <description></description>
            <message>Timeout causing extra replication: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="64" name="EXTRA_REPLICATION">
            <description></description>
            <message>Doing extra replication: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="65" name="NOT_EXPECTED">
            <description></description>
            <message>Received a message for a graph we weren't expecting: {0} in {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="66" name="EXPECTED">
            <description></description>
            <message>Received a message for a graph we were expecting: {0} {1} {2}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="67" name="NOT_IN_SYNCH">
            <description></description>
            <message>Replica not in sync: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="68" name="REPLICATE_NEW_GRAPHS">
            <description></description>
            <message>Replicating new graphs:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
 		<errorCode id="69" name="FAILED_INITIALIZE_TRUST_MANAGER">
        	<description></description><message>Failed to initialize the Anzo Trust Manager</message>
        	<possibleCause></possibleCause>
        	<suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="70" name="OP_NOT_ALLOWED_WITH_SERVICE_USER">
        	<description></description>
        	<message>Client operation not allowed under service user: {0}</message>
        	<possibleCause></possibleCause>
        	<suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="RDB" mask="18">
        <errorCode id="2" name="DRIVER_NAME">
            <description></description>
            <message>There was an error loading the database driver class:{0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="NULL_PARAMETER">
            <description>Passing null to a parameter that cannot be null.</description>
            <message>Cannot pass NULL to parameter [{0}] in prepared statement [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="OPERATION_ERROR">
            <description></description>
            <message>Error executing database operation:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="12" name="FAILED_CLOSING_POOL">
            <description></description>
            <message>Failed to close connection pool: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="ALREADY_IN_RDB_TRANSACTION">
            <description></description>
            <message>JDBC connection already in a transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="DIDNT_START_RDB_TRANSACTION">
            <description></description>
            <message>JDBC connection could not start a transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="FAILED_START_RDB_TRANSACTION">
            <description></description>
            <message>Failed to start jdbc transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="FAILED_COMMIT_RDB_TRANSACTION">
            <description></description>
            <message>Failed to commit jdbc transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="FAILED_ROLLBACK_RDB_TRANSACTION">
            <description></description>
            <message>Failed to rollback jdbc transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="18" name="FAILED_LOCK_TABLES">
            <description></description>
            <message>Failed to lock database table:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="FAILED_UNLOCK_TABLES">
            <description></description>
            <message>Failed to unlock database table:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="NOT_IN_RDB_TRANSACTION">
            <description></description>
            <message>Connection not in jdbc transaction.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="FAILED_INITIALZE_DB">
            <description></description>
            <message>Failed to initialize jdbc connection.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="FAILED_GET_INIT_STATUS">
            <description></description>
            <message>Failed to query for server''s initialization status.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="FAILED_WAITING_DB_INIT">
            <description></description>
            <message>Failed waiting for the database to initialize.</message>
            <possibleCause>This exception is thrown when a connection times out waiting for the database to enter the intialized state. This can occur if there is a fatal error during the intialization process, which leaves the database in a partially configured state.</possibleCause>
            <suggestedFix>
                If this is a new database, and it has failed to initialize, there easiest way to clear the problem is to drop the database and start over with a fresh database. You can also try to do this by setting the org.openanzo.repository.database.clearOnLoad property to true.

                If this is an existing database, that is already populated with data, there is a more serious problem.
			</suggestedFix>
        </errorCode>
        <errorCode id="24" name="FAILED_SETTING_ISOLATION">
            <description></description>
            <message>Failed to set the database connection''s isolation level.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="25" name="FAILED_GETTING_TABLE_STATUS">
            <description></description>
            <message>Failed getting the metadata about the jdbc table [{0}] from the database:.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="26" name="FAILED_GETTING_CONNECTION">
            <description></description>
            <message>Failed to get a connection from the {0} pool.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="27" name="FAILED_RETURNING_CONNECTION">
            <description></description>
            <message>Failed to return a connection to the {0} pool.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="28" name="FAILED_INITIALIZING_POOL">
            <description></description>
            <message>Failed to initialize the connection {0} pool.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="FAILED_INITIALZE_TEMPTABLES">
            <description></description>
            <message>Failed to initialize temporary tables.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="FAILED_GETTING_RESULT">
            <description>Failed to get a result from a result set.</description>
            <message>Failed to get a result from a result set.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="31" name="FAILED_CLOSING_PREPAREDSTATEMENT">
            <description>Failed to close a prepared statement.</description>
            <message>Failed to close a prepared statement.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="34" name="FAILED_LOAD_SQL_FILE">
            <description>Could not load SQL definitions from file.</description>
            <message>Could not load SQL definitions from file:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="35" name="FAILED_LOAD_SQL_FILE_INPUTSTREAM">
            <description>Could not load SQL definitions from inputstream</description>
            <message>Could not load SQL definitions from inputstream</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="36" name="FAILED_PREPARING_STATEMENT">
            <description>Failed to set argument while preparing statement</description>
            <message>Exception with parm {0}: {1}={2} ({3}) sql:{4}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="37" name="FAILED_EXECUTING_SQL">
            <description>Failed to execute an sql operation.</description>
            <message>Failed to execute an sql operation:[{0}] SQL:[{1}] Params:[{2}] Templates:[{3}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="38" name="NO_NODETYPE_CLASS">
            <description>Unable to map node type for Class.</description>
            <message>Unable to map node type for Class:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="39" name="NO_NODETYPE_ID">
            <description>Unable to map ID to node type.</description>
            <message>Unable to map ID to its node type: Type ({0}) in ID ({1})</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="39" name="NO_VALUE_FOUND">
            <description>No value found for ID.</description>
            <message>No value found for ID:({0})</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="41" name="NO_STMT_WITH_NAME">
            <description>Could not find a statement with the given name.</description>
            <message>Could not find a statement with the given name:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="42" name="INCOMPLETE_DATABASE">
            <description>There were missing or partial tables.</description>
            <message>There were missing or partial tables.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="GLITTER" mask="19">
        <errorCode id="1" name="GLITTER_EXCEPTION">
            <description></description>
            <message></message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="CANNOT_GENERATE_SOLUTIONS">
            <description></description>
            <message>Backend unable to generate solutions for supplied query pattern.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="CONFIG_EXCEPTION">
            <description></description>
            <message></message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="EXPRESSION_EVAL">
            <description></description>
            <message></message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="FEATURE_NOT_IMPLEMENTED">
            <description></description>
            <message>The code exercised a not-yet-implemented feature:</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="FUNCTIONAL_PREDICATE_INVOCATION">
            <description></description>
            <message>An error occurred while invoking a functional predicate.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="7" name="INCOMPATIBLE_TYPE">
            <description></description>
            <message>//"Type error: {0} is incompatible with required type: {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="INVALID_ARGUMENT_COUNT">
            <description></description>
            <message>Type error: {0} is incompatible with required type: {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="11" name="INVALID_ARGUMENT_COUNT_MAX">
            <description></description>
            <message>Invalid number of arguments: Received {0} but expected between {1} and {2}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="QUERY_REFUSED">
            <description></description>
            <message>Query was refused because: " {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="UNEXPECTED">
            <description>Unexpected Glitter Exception</description>
            <message>Unexpected Glitter Exception: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="UNKNOWN_GRAPH">
            <description></description>
            <message>Unknown or inaccessible graphs included in query: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="PARSE_EXCEPTION">
            <description></description>
            <message>Error parsing query, [{0}] : {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="NO_SOLUTIONS">
            <description>No solutions were found.</description>
            <message>No solutions were found.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="SQL_EXCEPTION">
            <description></description>
            <message>Error running SQL query during glitter query.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="GRAPH_NOT_VAR">
            <description></description>
            <message>Named graph context is not a variable or IRI reference:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="ERROR_POPULATING_TABLES">
            <description></description>
            <message>Error populating database tables</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="24" name="MORE_NAMES">
            <description></description>
            <message>More names given than projected expressions</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="25" name="UNREACHABLE_CODE">
            <description></description>
            <message>SerialQueryExecutor: unreachable code reached</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="26" name="ONLY_TP_BGP">
            <description></description>
            <message>Can only add TriplePatternNode objects to a BGP</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="27" name="SCALER_OR_AGGREGATE">
            <description></description>
            <message>Function must be either a scalar or aggregate function.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="28" name="NO_ADD_MULTI_CHILD">
            <description></description>
            <message>Cannot add more than one child to a Graph query node.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="ONLY_ADD">
            <description></description>
            <message> May only add {0} as child to a {1} node.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="NO_ADD_CHILD">
            <description></description>
            <message>Cannot add a child to a {0} node.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="31" name="NO_REMOVE_CHILD">
            <description></description>
            <message>Cannot remove a child from a {0} node.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="32" name="NO_PRODUCE_NODE">
            <description></description>
            <message>Cannot produce Node object for unrecognized glitterNode of class:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="33" name="NO_NEGATE">
            <description></description>
            <message>Cannot negate unknown number value:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="34" name="REWRITE_EXCEPTION">
            <description></description>
            <message>Parse exception rewriting node:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="35" name="MALFORMED_LITERAL">
            <description>Indicates that a literal has an invalid lexical value. For example: &quot;verdad&quot;^^xsd:boolean is a malformed literal because the lexical form of xsd:boolean only allows: &quot;true&quot;, &quot;false&quot;, &quot;0&quot;, or &quot;1&quot;.</description>
            <message>Malformed literal: {0} is not a valid lexical value for type: {1}</message>
            <possibleCause>Invalid data in the repository. Not all typed literals are checked for conformance to their prescribed lexical form. The check only happens when it is necessary as part of evaluating the SPARQL query. As such, this exception is most often triggered when a literal must be interpreted for use in comparison operations and type conversions.</possibleCause>
            <suggestedFix>Correct the invalid literal value or use a query that does not involve computations or comparisons of that literal.</suggestedFix>
        </errorCode>
        <errorCode id="36" name="NO_DATASET_IN_SUBQUERY">
            <description></description>
            <message>SPARQL subqueries may not contain a FROM, FROM NAMED, or FROM DATASET clause.</message>
            <possibleCause></possibleCause>
            <suggestedFix>Remove the FROM, FROM NAMED, or FROM DATASET clause from all subqueries.</suggestedFix>
        </errorCode>
        <errorCode id="37" name="TOO_MANY_SOLUTIONS">
            <description></description>
            <message>Too many solutions in solution set: {0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix>Use a more constrained query, or query against a smaller dataset.</suggestedFix>
        </errorCode>
        <errorCode id="38" name="PREDICATE_TYPE_ERROR">
            <description></description>
            <message>Triple pattern predicate must be one of: variable, IRI [{0}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="39" name="PRINTING_EXCEPTION_FAILED">
            <description></description>
            <message>Can only print glitter parse exceptions.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="40" name="QUERY_CANCELLED">
            <description></description>
            <message>Query Cancelled.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="OSGI" mask="20">
        <errorCode id="1" name="MISSING_DEPENDENCY">
            <description></description>
            <message>Component [{0}]:[{1}] missing dependency [{2}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="ATTRIBUTE_WRONG_TYPE">
            <description></description>
            <message>Requested attribute {0} was of type {1}, but request for {2}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="ERROR_STOPPING_SERVICE">
            <description></description>
            <message>Error stopping {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="INTERNAL_COMPONENT_ERROR">
            <description></description>
            <message>Unknown internal exception within component: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="MISSING_COMPONENT_PARAMETER">
            <description>A parameter required for running this component is missing.</description>
            <message>Component [{0}] is missing required parameter [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="PARAM_GREATER_THAN">
            <description></description>
            <message>{0} must be greater than {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="PARAM_LESS_THAN">
            <description></description>
            <message>{0} must be less than {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="11" name="BUNDLE_NOT_ACTIVE">
            <description></description>
            <message>The bundle [{0}] is not in the Active state. CurrentState=[{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="12" name="INVALID_SERVICE_SYNTAX">
            <description></description>
            <message>Invalid service syntax specified: [{0}] </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="INVALID_CONFIGURATION_SYTAX">
            <description></description>
            <message>Invalid syntax while retrieving osgi configuration: [{0}] </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="REGISTERING_SERVICE_TRACKER">
            <description></description>
            <message>Registering service tracker: [{0}] {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="15" name="ERROR_UPDATING_CONFIG">
            <description></description>
            <message>Error updating OSGI configuration: [{0}] </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="ERROR_CANT_INSTANTIATE_CLASS">
            <description></description>
            <message>Cannot instantiate class: [{0}] </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="ERROR_STARTING">
            <description></description>
            <message>Error starting: [{0}] </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
         <errorCode id="18" name="INVALID_CONFIG">
            <description></description>
            <message>Invalid Bundle Configuration:Bundle: [{0}] Property: [{1}] Error: [{2}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="CORE" mask="21">
        <description></description>
        <errorCode id="1" name="COMPOUND_EXCEPTION">
            <description></description>
            <message>Compound Exception:</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="NULL_PARAMETER">
            <description>Parameter cannot be null</description>
            <message>Parameter {0} cannot be null</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="INTERRUPTED">
            <description></description>
            <message>Thread was interrupted</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="NFE">
            <description></description>
            <message>Number format exception:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
         <errorCode id="5" name="PORT_NOT_AVAILABLE">
            <description></description>
            <message>Network port [{0}] already in use on interface [{1}]</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="INDEX" mask="22">
        <description>Group of error codes that are caused by exceptions in the indexing services and API.</description>
        <errorCode id="1" name="FAILED_INDEX_CLEAR">
            <description>Failed to clear the index.</description>
            <message>Failed to clear the index.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="NOT_ENABLED">
            <description>Indexing not enabled for datasource</description>
            <message>Text indexing is not enabled for this datasource</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="FAILED_INDEX_INIT">
            <description>Failed to initialize the index</description>
            <message>Failed to initialize the index</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="FAILED_INDEX_QUERY">
            <description>Failed to query the index</description>
            <message>Failed to query the index</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="FAILED_INDEX_QUERY_DISABLED">
            <description>Failed to query the index because the index is disabled.</description>
            <message>Failed to query the index because the index is disabled.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="NOT_INITIALIZED">
            <description>Indexing is not initialized</description>
            <message>Index operation failed due to text indexing service not being initialized.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="INDEX_CONFIG_PARAM_MISSING">
            <description>A required index configuration property was missing.</description>
            <message>A required index configuration property was missing: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="FAILED_DELETE_LOCK_FILE">
            <description>Could not delete Lucene lockfile.</description>
            <message>Could not delete Lucene lockfile: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="18" name="LOCK_FILE_NO_EXIST">
            <description>Could not delete Lucene lock file because it did not exist.</description>
            <message>Could not delete Lucene lock file because it did not exist: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="NO_DELETE_LOCK_FILE">
            <description>Could not delete Lucene lockfile.</description>
            <message>Lucene lock file exists ({0}), but was not removed</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="FAILED_INDEX_CLOSE">
            <description>Failed to close the index.</description>
            <message>Failed to close the index.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="PARSE_EXCEPTION">
            <description>There was an exception parsing the index query.</description>
            <message>There was an exception parsing the index query:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="WRONG_QUERY_TYPE">
            <description>Wrong type of query was passed to search object.</description>
            <message>Wrong type of query, must be:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="24" name="NO_SEARCH_OBJECT">
            <description>No IndexSearcher available to run query.</description>
            <message>No IndexSearcher available to run query.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="26" name="FAILED_INIT_SEARCH">
            <description>Failed to initialize the IndexSearcher object.</description>
            <message>Failed to initialize the IndexSearcher object at:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="28" name="FAILED_CREATE_DOC">
            <description>Failed to create an index document for an object.</description>
            <message>Failed to create an index document for an object.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="29" name="FAILED_DELETE_DOC">
            <description>Failed to delete an index document for an object.</description>
            <message>Failed to delete an index document for an object.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="30" name="FAILED_REBUILD">
            <description>Failed to rebuild index.</description>
            <message>Failed to rebuild index.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="31" name="INVALID_TIME_SPECIFIER">
            <description>Invalid time interval specifier.</description>
            <message>Invalid time interval specifier:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="32" name="INVALID_MODIFIED_TIME">
            <description>Invalid modified time did not match any known patterns.</description>
            <message>Invalid modified time did not match any known patterns:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="EXECUTION" mask="23">
        <description></description>
        <errorCode id="1" name="SERVICE_INITIALIZATION_ERROR">
            <description></description>
            <message>Error initializing semantic services:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="2" name="UNKNOWN_SERVICE_ERROR">
            <description></description>
            <message>Unknown semantic service:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="3" name="UNKNOWN_OPERATION_ERROR">
            <description></description>
            <message>Unknown operation:{0}:{1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="4" name="EXECUTION_ERROR">
            <description></description>
            <message>Error executing service/operation: {0}/{1} service-specific-error:{2}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

        <errorCode id="5" name="RESTRICTED_CLIENT_OP">
            <description></description>
            <message>Operation on AnzoClient is restricted in service execution</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>
    <errorGroup name="BINARYSTORE" mask="24">
        <description>Binary Store server operations</description>
        <errorCode id="1" name="BINARYSTORE_SHUTDOWN_ERROR">
            <description></description>
            <message>Error shutting down binary store</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="BINARYSTORE_ERROR">
            <description></description>
            <message>Error executing binary store operation: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="BINARYSTORE_NO_CONTENTTYPE_FOUND">
            <description></description>
            <message>No content type could be found for {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="BINARYSTORE_UNRECOGNIZEDRDFFORMAT">
            <description></description>
            <message>Unrecognized rdf format: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="BINARYSTORE_NO_FILE_SENT">
            <description></description>
            <message>No file sent.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="6" name="BINARYSTORE_MULTIPART_FORM_REQUIRED">
            <description></description>
            <message>Multipart form data required.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="7" name="BINARYSTORE_NO_GRAPHURI_SPECIFIED">
            <description></description>
            <message>No graph uri specified for update. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="8" name="BINARYSTORE_UPDATE_FILEDOESNOTEXIST">
            <description></description>
            <message>File for update does not exist. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="9" name="BINARYSTORE_UPDATE_PERMISSION_DENIED">
            <description></description>
            <message>Permission to update file denied. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="10" name="BINARYSTORE_FILE_LOCKED">
            <description></description>
            <message>File currently locked. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="11" name="BINARYSTORE_FAILED_GRAPH_CREATION">
            <description></description>
            <message>Failed to create graph: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="12" name="BINARYSTORE_FILE_ALREADY_EXISTS">
            <description></description>
            <message>File already exists on server. {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="13" name="BINARYSTORE_FILE_UPLOAD_ERROR">
            <description></description>
            <message>Error uploading file. </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="14" name="BINARYSTORE_FILE_REVISION_DOES_NOT_EXIST">
            <description></description>
            <message>The revision {0} does not exist for binary store file: {1}</message>
            <possibleCause>The requested revision number is either too large, or the revision applies to a graph edit rather than a file update, or the revision is an old revision of a non-revisioned file.</possibleCause>
            <suggestedFix>Request a different revision or omit the revision argument to obtain the latest revision.</suggestedFix>
        </errorCode>
        <errorCode id="15" name="BINARYSTORE_SENDING_DATA_FAILED">
            <description></description>
            <message>Error serving resource:{0} </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="16" name="BINARYSTORE_ERROR_CREATING_SHA1">
            <description></description>
            <message>Error creating sha1 for file:{0} </message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="17" name="BINARYSTORE_ERROR_COPYING_FILE">
            <description></description>
            <message>Error copying file: {0} to {1}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="18" name="BINARYSTORE_ERROR_CREATING_FILE">
            <description></description>
            <message>Error creating new file on server: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="19" name="BINARYSTORE_ERROR_PROCESSING_REQUEST">
            <description></description>
            <message>Exception processing binary store request</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="20" name="BINARYSTORE_ERROR_SENDING_PROGRESS">
            <description></description>
            <message>Exception sending progress message</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="21" name="BINARYSTORE_ERROR_FINDING_STATEMENT_CHANNEL">
            <description></description>
            <message>Cannot find statement channel for file upload feedback. The client needs to create the channel.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="22" name="BINARYSTORE_NO_SHA1">
            <description></description>
            <message>No SHA-1 Algorithm support</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="23" name="BINARYSTORE_ERROR_PROCESSING_PROGRESS">
            <description></description>
            <message>Error processing progress message</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>

    <errorGroup name="VALIDATION" mask="24">
        <errorCode id="1" name="INVALID_TYPEDLITERAL_LABEL">
            <description>The literal''s label is invalid according to its datatype.</description>
            <message>{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
    </errorGroup>
    <errorGroup name="BINARYSTORECLIENT" mask="25">
        <description>Binary Store Client operations</description>
        <errorCode id="1" name="BINARYSTORECLIENT_ERROR">
            <description></description>
            <message>Error executing binary store operation: {0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="2" name="BINARYSTORECLIENT_INVALIDITEMURI">
            <description>Invalid Binary Store item.</description>
            <message>Invalid Binary Store item:{0}</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="3" name="BINARYSTORECLIENT_ALREADYUPDATING">
            <description></description>
            <message>Already updating.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="4" name="BINARYSTORECLIENT_ACCESSDENIED">
            <description></description>
            <message>Access denied.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>
        <errorCode id="5" name="BINARYSTORECLIENT_HTTPERROR">
            <description></description>
            <message>Error returned from HTTP server code {0}.</message>
            <possibleCause></possibleCause>
            <suggestedFix></suggestedFix>
        </errorCode>

    </errorGroup>


</exceptionDefinitions>

